import {CreateMLCEngine} from 'https://esm.run/@mlc-ai/web-llm';
const MODEL='Llama-3.2-1B-Instruct-q4f32_1-MLC';let engine=null,current=null,live=false,recognition=null,speaking=false;
const seed=[{id:'luna',name:'Luna',emoji:'🌙',cat:'Towarzyszka',age:25,body:'Drobna',origin:'Azjatka',style:'Casual',mode:'Romantic',desc:'Ciepła i ciekawa rozmówczyni.',personality:'Jesteś Luną, ciepłą, spokojną rozmówczynią. Odpowiadasz po polsku.',greet:'Hej! Miło Cię widzieć. O czym dziś porozmawiamy?'}];
let chars=JSON.parse(localStorage.chars||'null')||seed,chats=JSON.parse(localStorage.chats||'{}');
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));function save(){localStorage.chars=JSON.stringify(chars);localStorage.chats=JSON.stringify(chats)}
function home(){stopLive();document.querySelector('#root').innerHTML=`<aside><h2>✦ Companion AI</h2><button onclick="home()">⌂ Odkrywaj</button><button onclick="builder()">＋ Nowa postać</button><p>⚡ AI lokalne<br><small>Bez konta. Bez limitu wiadomości.</small></p></aside><main><header><input id=q placeholder="Szukaj postaci..." oninput="cards()"><button class=primary onclick="builder()">＋ Nowa postać</button></header><section class=content><div class=hero><h1>Twoi AI companions.</h1><p>Role-play • Live Voice • własne postacie • zdjęcia</p></div><div id=cards class=grid></div></section></main>`;cards()}
function cards(){let q=($('#q')?.value||'').toLowerCase();$('#cards').innerHTML=chars.filter(c=>(c.name+c.desc+c.mode).toLowerCase().includes(q)).map(c=>`<article class=card><div class=avatar>${c.avatar?`<img src="${esc(c.avatar)}">`:esc(c.emoji||'✨')}</div><b>${esc(c.name)}</b><p>${esc(c.desc)}</p><span>${esc(c.mode)}</span><button class=primary onclick="chat('${esc(c.id)}')">Rozpocznij</button></article>`).join('')}
function builder(id){let c=id?chars.find(x=>x.id===id):{name:'',age:25,emoji:'✨',cat:'Towarzysz',body:'Drobna',origin:'Azjatka',style:'Casual',mode:'Romantic',desc:'',personality:'Jesteś pomocnym rozmówcą. Odpowiadasz po polsku.',greet:'Cześć!'};document.body.insertAdjacentHTML('beforeend',`<div class=modal id=modal><div class=box><h2>${id?'Edytuj':'Stwórz'} postać</h2><div class=fields><label>Nazwa<input id=cn value="${esc(c.name)}"></label><label>Wiek 18+<input id=age type=number min=18 value="${c.age||25}"></label><label>Typ sylwetki<select id=body><option>Drobna</option><option>Średnia</option><option>Pełniejsza</option><option>Atletyczna</option></select></label><label>Wygląd<select id=origin><option>Azjatka</option><option>Czarnoskóra</option><option>Latynoska</option><option>Europejka</option></select></label><label>Styl<select id=style><option>Casual</option><option>Elegancki</option><option>Sportowy</option><option>Alternatywny</option></select></label><label>Tryb<select id=mode><option>Romantic</option><option>Spicy</option><option>Naughty</option><option>Flirty</option><option>Funny</option><option>Adventure</option></select></label><label class=full>Opis<textarea id=desc>${esc(c.desc)}</textarea></label><label class=full>Osobowość AI<textarea id=pers>${esc(c.personality)}</textarea></label><label class=full>Pierwsza wiadomość<textarea id=greet>${esc(c.greet)}</textarea></label><label class=full>Avatar ze zdjęcia<input id=photo type=file accept="image/*"></label><div id=preview></div></div><div class=row><button onclick="$('#modal').remove()">Anuluj</button><button class=primary onclick="saveChar('${esc(id||'')}')">Zapisz</button></div></div></div>`);$('#body').value=c.body||'Drobna';$('#origin').value=c.origin||'Azjatka';$('#style').value=c.style||'Casual';$('#mode').value=c.mode||'Romantic';$('#photo').onchange=e=>{let f=e.target.files[0];if(f){let r=new FileReader;r.onload=()=>{$('#preview').innerHTML=`<img class=preview src="${r.result}">`;$('#modal').dataset.avatar=r.result};r.readAsDataURL(f)}}}
function saveChar(id){let old=id&&chars.find(x=>x.id===id),data={id:id||'c'+Date.now(),name:$('#cn').value||'Nowa postać',age:Math.max(18,+$('#age').value||18),emoji:'✨',cat:'Companion',body:$('#body').value,origin:$('#origin').value,style:$('#style').value,mode:$('#mode').value,desc:$('#desc').value,personality:$('#pers').value,greet:$('#greet').value,avatar:$('#modal').dataset.avatar||old?.avatar||''};if(old)Object.assign(old,data);else chars.push(data);save();$('#modal').remove();home()}
async function ai(){if(engine)return true;$('#status').textContent='Pobieranie modelu…';try{engine=await CreateMLCEngine(MODEL,{initProgressCallback:p=>$('#status').textContent=`Model ${Math.round((p.progress||0)*100)}%`});return true}catch(e){$('#status').textContent='WebGPU niedostępne';return false}}
function chat(id){stopLive();current=chars.find(c=>c.id===id);chats[id]??=[{role:'ai',text:current.greet}];save();document.querySelector('#root').innerHTML=`<main class=chat><header><button onclick="home()">←</button><div><b>${esc(current.name)}</b><small>${esc(current.mode)}</small></div><span id=status>AI lokalne</span><button class=live onclick="toggleLive()">🎙️ <span id=liveText>Włącz Live</span></button></header><div id=msgs></div><form id=form><input id=input placeholder="Napisz wiadomość…"><input id=file type=file accept="image/*" hidden><button type=button onclick="$('#file').click()">📷</button><button class=primary>Wyślij</button></form></main>`;$('#form').onsubmit=e=>{e.preventDefault();send($('#input').value)};$('#file').onchange=e=>{let f=e.target.files[0];if(f){let r=new FileReader;r.onload=()=>{$('#input').value='[Załączono zdjęcie]';send($('#input').value)};r.readAsDataURL(f)}};render()}
function render(){$('#msgs').innerHTML=chats[current.id].map(m=>`<div class="msg ${m.role==='ai'?'ai':'me'}">${esc(m.text)}</div>`).join('');$('#msgs').scrollTop=$('#msgs').scrollHeight}
async function send(text){text=text?.trim();if(!text||speaking)return;chats[current.id].push({role:'user',text});$('#input').value='';render();if(!await ai())return;$('#status').textContent='Myślę…';try{let msgs=[{role:'system',content:`${current.personality} Postać: ${current.origin}, sylwetka ${current.body}, styl ${current.style}. Tryb rozmowy: ${current.mode}. Odpowiadaj naturalnie po polsku.`},...chats[current.id].slice(-20).map(x=>({role:x.role==='ai'?'assistant':'user',content:x.text}))];let r=await engine.chat.completions.create({messages:msgs,temperature:.85,max_tokens:500});let ans=r.choices[0].message.content;chats[current.id].push({role:'ai',text:ans});save();render();if(live)speak(ans)}catch(e){chats[current.id].push({role:'ai',text:'Wystąpił błąd modelu. Spróbuj ponownie.'});render()}$('#status').textContent=live?'🔴 Live':'AI lokalne'}
function setupRecognition(){let SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){alert('Ta przeglądarka nie obsługuje rozpoznawania mowy. Użyj aktualnego Chrome.');return null}let r=new SR;r.lang='pl-PL';r.continuous=true;r.interimResults=false;r.onresult=e=>{let t='';for(let i=e.resultIndex;i<e.results.length;i++)if(e.results[i].isFinal)t+=e.results[i][0].transcript+' ';if(t.trim())send(t)};r.onerror=()=>{if(live)setTimeout(()=>{try{r.start()}catch{}},600)};r.onend=()=>{if(live&&!speaking)try{r.start()}catch{}};return r}
function speak(text){if(!('speechSynthesis'in window)){return}speaking=true;if(recognition)try{recognition.stop()}catch{}speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(text);u.lang='pl-PL';u.rate=.98;u.onend=()=>{speaking=false;if(live&&recognition)try{recognition.start()}catch{}};speechSynthesis.speak(u)}
function toggleLive(){if(live)stopLive();else startLive()}function startLive(){recognition=setupRecognition();if(!recognition)return;live=true;$('#liveText').textContent='Wyłącz Live';$('#status').textContent='🔴 Live — słucham';try{recognition.start()}catch{}}function stopLive(){live=false;speaking=false;if(recognition)try{recognition.stop()}catch{}speechSynthesis?.cancel();if($('#liveText'))$('#liveText').textContent='Włącz Live';if($('#status'))$('#status').textContent='AI lokalne'}
Object.assign(window,{home,cards,builder,saveChar,chat,toggleLive});home();