const pics=['https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=700&q=80','https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=700&q=80','https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=700&q=80','https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=700&q=80'];
const seed=[
{id:'luna',name:'Luna',age:25,mode:'Romantic',style:'Casual',desc:'Ciepła i spokojna.',personality:'Ciepła, uważna i naturalna.',avatar:pics[0]},
{id:'mia',name:'Mia',age:26,mode:'Spicy',style:'Glamour',desc:'Pewna siebie i flirtująca.',personality:'Pewna siebie, dowcipna i lekko flirtująca.',avatar:pics[1]},
{id:'aiko',name:'Aiko',age:23,mode:'Playful',style:'Anime',desc:'Energiczna persona anime.',personality:'Energiczna, zabawna i figlarna.',avatar:pics[2]},
{id:'raven',name:'Raven',age:27,mode:'Naughty',style:'Goth',desc:'Tajemnicza i zadziorna.',personality:'Bezpośrednia, z mrocznym humorem i lekkim droczeniem.',avatar:pics[3]},
{id:'sofia',name:'Sofia',age:29,mode:'Flirty',style:'Pin-up',desc:'Pogodna i charyzmatyczna.',personality:'Pogodna, pewna siebie i dowcipna.',avatar:pics[1]},
{id:'elena',name:'Elena',age:31,mode:'Romantic',style:'Elegancki',desc:'Dojrzała i romantyczna.',personality:'Spokojna, empatyczna i romantyczna.',avatar:pics[2]}
];
let chars=JSON.parse(localStorage.getItem('chars')||'null')||seed;let chats=JSON.parse(localStorage.getItem('chats')||'{}');let current=null,live=false,recognition=null,speaking=false,busy=false;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));function save(){localStorage.setItem('chars',JSON.stringify(chars));localStorage.setItem('chats',JSON.stringify(chats))}
function css(){const s=document.createElement('style');s.textContent=`*{box-sizing:border-box}body{margin:0;background:#08090d;color:#eee;font-family:system-ui}button,input,textarea,select{font:inherit}button{border:0;border-radius:12px;padding:11px 14px;background:#1b1e28;color:#fff;cursor:pointer}.primary{background:#7457ff}.live{background:#bd315b}.layout{min-height:100vh;padding:22px;max-width:1200px;margin:auto}.top{display:flex;gap:10px;align-items:center;margin-bottom:22px}.top input{flex:1;background:#10131a;color:#fff;border:1px solid #303544;border-radius:12px;padding:12px}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(190px,1fr));gap:16px}.card{background:#12151d;border:1px solid #292d38;border-radius:18px;padding:12px;display:flex;flex-direction:column;gap:8px}.avatar{height:230px;border-radius:14px;overflow:hidden;background:#191c25}.avatar img{width:100%;height:100%;object-fit:cover}.muted{opacity:.65;font-size:13px}.chat{height:100vh;display:flex;flex-direction:column;max-width:900px;margin:auto}.chathead{display:flex;align-items:center;gap:10px;padding:12px;border-bottom:1px solid #252936}.chathead .status{margin-left:auto;font-size:12px}.msgs{flex:1;overflow:auto;padding:18px}.msg{max-width:80%;padding:12px 14px;border-radius:16px;margin:8px 0;white-space:pre-wrap}.ai{background:#171a23}.me{background:#4b3e88;margin-left:auto}.typing{opacity:.65}.composer{display:flex;gap:8px;padding:12px;border-top:1px solid #252936}.composer input{flex:1;background:#10131a;color:#fff;border:1px solid #303544;border-radius:12px;padding:12px}.modal{position:fixed;inset:0;background:#000b;display:grid;place-items:center;padding:16px;z-index:10}.box{width:min(700px,100%);max-height:90vh;overflow:auto;background:#11141c;border:1px solid #292d38;border-radius:20px;padding:20px}.fields{display:grid;grid-template-columns:1fr 1fr;gap:12px}.fields label{display:flex;flex-direction:column;gap:6px}.fields input,.fields select,.fields textarea{background:#0a0c11;color:#fff;border:1px solid #303544;border-radius:10px;padding:10px}.full{grid-column:1/-1}.row{display:flex;justify-content:flex-end;gap:8px;margin-top:16px}.provider{display:flex;gap:8px;align-items:center;margin:12px 0;padding:12px;background:#11141c;border:1px solid #292d38;border-radius:14px}.provider select{background:#0a0c11;color:#fff;border:1px solid #303544;border-radius:10px;padding:9px}@media(max-width:700px){.layout{padding:14px}.fields{grid-template-columns:1fr}.avatar{height:200px}}`;document.head.appendChild(s)}
function home(){stopLive();$('#root').innerHTML=`<div class=layout><div class=top><b>✦ Companion AI</b><input id=search placeholder="Szukaj postaci..." oninput=renderCards()><button class=primary onclick=builder()>＋ Nowa postać</button></div><div class=provider><b>AI:</b><select id=provider onchange="localStorage.setItem('provider',this.value)"><option value="demo">Demo — bez klucza</option><option value="groq">Groq — darmowy limit</option><option value="gemini">Gemini — darmowy limit</option><option value="openai">OpenAI — własny klucz</option></select><span class=muted id=providerHint></span></div><h1>Twoi AI companions</h1><p class=muted>Wybierz Demo, aby testować bez płatnego API. Klucze pozostałych dostawców są przechowywane po stronie serwera.</p><div id=cards class=grid></div></div>`;$('#provider').value=localStorage.getItem('provider')||'demo';updateProviderHint();renderCards()}
function updateProviderHint(){const v=$('#provider')?.value;const h=$('#providerHint');if(h)h.textContent=v==='demo'?'Bez klucza — tryb demonstracyjny':v==='groq'?'Wymaga GROQ_API_KEY':v==='gemini'?'Wymaga GEMINI_API_KEY':'Wymaga OPENAI_API_KEY'}
function renderCards(){const q=($('#search')?.value||'').toLowerCase();$('#cards').innerHTML=chars.filter(c=>(c.name+c.mode+c.style+c.desc).toLowerCase().includes(q)).map(c=>`<article class=card><div class=avatar><img src="${esc(c.avatar)}"></div><b>${esc(c.name)}, ${c.age}</b><div>${esc(c.desc)}</div><span class=muted>${esc(c.mode)} · ${esc(c.style)}</span><button class=primary onclick="openChat('${esc(c.id)}')">Rozmowa</button></article>`).join('')}
function builder(){document.body.insertAdjacentHTML('beforeend',`<div class=modal id=modal><div class=box><h2>Nowa dorosła persona</h2><div class=fields><label>Nazwa<input id=bn value="Nowa postać"></label><label>Wiek<input id=ba type=number min=18 value=25></label><label>Persona<select id=bm><option>Romantic</option><option>Spicy</option><option>Naughty</option><option>Flirty</option><option>Playful</option><option>Funny</option><option>Adventure</option></select></label><label>Styl<select id=bs><option>Realistyczny</option><option>Anime</option><option>Goth</option><option>Fantasy</option><option>Pin-up</option><option>Fashion</option></select></label><label class=full>Opis<textarea id=bd>Naturalna, rozmowna i reagująca osobiście na rozmowę.</textarea></label><label class=full>Osobowość<textarea id=bp>Jesteś dorosłą fikcyjną postacią. Odpowiadasz po polsku, naturalnie, pamiętasz kontekst i rozwijasz rozmowę.</textarea></label><label class=full>Avatar URL<input id=bi value="${pics[0]}"></label></div><div class=row><button onclick="$('#modal').remove()">Anuluj</button><button class=primary onclick=saveChar()>Zapisz</button></div></div></div>`)}
function saveChar(){chars.push({id:'c'+Date.now(),name:$('#bn').value||'Postać',age:Math.max(18,+$('#ba').value||18),mode:$('#bm').value,style:$('#bs').value,desc:$('#bd').value,personality:$('#bp').value,avatar:$('#bi').value||pics[0]});save();$('#modal').remove();home()}
function openChat(id){stopLive();current=chars.find(c=>c.id===id);chats[id]??=[];save();$('#root').innerHTML=`<div class=chat><header class=chathead><button onclick=home()>←</button><div><b>${esc(current.name)}, ${current.age}</b><div class=muted>${esc(current.mode)} · ${esc(current.style)}</div></div><span id=status class=status>Gotowy</span><button class=live onclick=toggleLive() id=liveBtn>🎙️ Live</button></header><div id=msgs class=msgs></div><form id=form class=composer><input id=input autocomplete=off placeholder="Napisz wiadomość..."><button class=primary>Wyślij</button></form></div>`;$('#form').onsubmit=e=>{e.preventDefault();send($('#input').value)};renderMsgs()}
function renderMsgs(){const b=$('#msgs');if(!b)return;b.innerHTML=chats[current.id].map(m=>`<div class="msg ${m.role==='assistant'?'ai':'me'}">${esc(m.text)}</div>`).join('');b.scrollTop=b.scrollHeight}
async function send(text){text=String(text||'').trim();if(!text||busy)return;busy=true;chats[current.id].push({role:'user',text});save();renderMsgs();$('#status').textContent='Myślę…';const typ=document.createElement('div');typ.id='typing';typ.className='msg ai typing';typ.textContent='Piszę…';$('#msgs').append(typ);try{const provider=localStorage.getItem('provider')||'demo';const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider,persona:current,messages:chats[current.id].map(m=>({role:m.role==='assistant'?'assistant':'user',content:m.text}))})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Błąd API');chats[current.id].push({role:'assistant',text:d.reply});save();$('#status').textContent=live?'🔴 Live':'Gotowy';$('#typing')?.remove();renderMsgs();if(live)speak(d.reply)}catch(e){$('#typing')?.remove();chats[current.id].push({role:'assistant',text:'Nie udało się uzyskać odpowiedzi: '+e.message});save();renderMsgs();$('#status').textContent='Błąd'}finally{busy=false}}
function setupRecognition(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){alert('Ta przeglądarka nie obsługuje rozpoznawania mowy. Użyj Chrome.');return null}const r=new SR();r.lang='pl-PL';r.continuous=true;r.interimResults=false;r.onresult=e=>{let t='';for(let i=e.resultIndex;i<e.results.length;i++)if(e.results[i].isFinal)t+=e.results[i][0].transcript+' ';if(t.trim()&&!busy&&!speaking)send(t)};r.onerror=()=>{if(live&&!busy&&!speaking)setTimeout(()=>{try{r.start()}catch{}},800)};r.onend=()=>{if(live&&!busy&&!speaking)setTimeout(()=>{try{r.start()}catch{}},250)};return r}
function speak(text){if(!('speechSynthesis'in window)){busy=false;return}speaking=true;if(recognition)try{recognition.stop()}catch{}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='pl-PL';u.rate=1;u.onend=()=>{speaking=false;if(live&&!busy)try{recognition?.start()}catch{}};u.onerror=()=>{speaking=false;if(live&&!busy)try{recognition?.start()}catch{}};speechSynthesis.speak(u)}
function toggleLive(){if(live){stopLive();return}recognition=setupRecognition();if(!recognition)return;live=true;$('#liveBtn').textContent='⏹ Zakończ Live';$('#status').textContent='🔴 Live — słucham';try{recognition.start()}catch{}}
function stopLive(){live=false;speaking=false;if(recognition)try{recognition.stop()}catch{}recognition=null;if('speechSynthesis'in window)speechSynthesis.cancel();if($('#liveBtn'))$('#liveBtn').textContent='🎙️ Live';if($('#status'))$('#status').textContent='Gotowy'}
Object.assign(window,{home,builder,saveChar,openChat,toggleLive,renderCards,updateProviderHint});css();home();