const STORE='afterdark_v2';
const state=JSON.parse(localStorage.getItem(STORE)||'null')||{chars:[],chats:{},mem:{},view:'discover'};
const avatars=['https://images.pexels.com/photos/3763188/pexels-photo-3763188.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/762020/pexels-photo-762020.jpeg?auto=compress&cs=tinysrgb&w=900'];
if(!state.chars.length)state.chars=[
{id:'luna',name:'Luna',age:25,tag:'Romantyczna',bio:'Ciepła, pewna siebie i ciekawa świata.',personality:'empatyczna, dowcipna, spontaniczna',backstory:'Fotografka podróżująca po Europie.',voice:'łagodnie i z humorem',avatar:avatars[0]},
{id:'raven',name:'Raven',age:27,tag:'Zadziorna',bio:'Pewna siebie, inteligentna i bezpośrednia.',personality:'odważna, ironiczna, lojalna',backstory:'Nocna DJ-ka i miłośniczka cyberpunku.',voice:'krótko, pewnie, z nutą ironii',avatar:avatars[1]},
{id:'aiko',name:'Aiko',age:24,tag:'Anime',bio:'Energiczna, czuła i trochę nieprzewidywalna.',personality:'wesoła, czuła, ciekawska',backstory:'Ilustratorka i graczka.',voice:'lekko, entuzjastycznie',avatar:avatars[2]},
{id:'sofia',name:'Sofia',age:29,tag:'Elegancka',bio:'Spokojna, dojrzała i bardzo rozmowna.',personality:'spokojna, inteligentna, flirtująca',backstory:'Projektantka wnętrz.',voice:'elegancko i spokojnie',avatar:avatars[3]}];
const save=()=>localStorage.setItem(STORE,JSON.stringify(state));
const esc=s=>String(s??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
const root=document.getElementById('root'); const find=id=>document.getElementById(id);
function shell(active='discover'){root.innerHTML=`<div class="app"><header><div class="brand">✦ <b>AfterDark</b><span>FREE</span></div><div class="topnav"><button data-v="discover">Discover</button><button data-v="chats">Chats</button><button data-v="create">＋ Create</button></div></header><main id="page"></main><nav class="bottom"><button data-v="discover">⌂<small>Discover</small></button><button data-v="chats">♡<small>Chats</small></button><button data-v="create">＋<small>Create</small></button><button data-v="gallery">▣<small>Gallery</small></button></nav></div>`;document.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>route(b.dataset.v));}
function route(v){state.view=v;save();shell(v);({discover:discover,chats:chats,create:creator,gallery:gallery}[v]||discover)();}
function discover(){find('page').innerHTML=`<section class="hero"><div class="eyebrow">18+ • AI COMPANIONS</div><h1>Znajdź swoją<br><em>ulubioną personę.</em></h1><p>Rozmawiaj, buduj relację i wracaj do historii rozmów. Dane postaci i czaty są zapisywane lokalnie w tej przeglądarce.</p><div class="actions"><button class="primary" onclick="route('create')">＋ Stwórz personę</button><button onclick="route('chats')">♡ Moje rozmowy</button></div></section><section class="section"><div class="sectionhead"><h2>Discover</h2><span>${state.chars.length} person</span></div><div class="cards">${state.chars.map(c=>card(c)).join('')}</div></section>`;}
function card(c){return `<article class="card"><img src="${esc(c.avatar)}" onerror="this.src='${avatars[0]}'"><div class="cardbody"><div class="tag">${esc(c.tag)}</div><h3>${esc(c.name)} <small>${c.age}</small></h3><p>${esc(c.bio)}</p><button class="primary" onclick="openChat('${c.id}')">Rozmawiaj</button></div></article>`}
function chats(){let ids=Object.keys(state.chats).filter(id=>state.chats[id]?.length);find('page').innerHTML=`<section class="section pagepad"><div class="sectionhead"><h1>Twoje rozmowy</h1></div>${ids.length?`<div class="chatlist">${ids.map(id=>{let c=state.chars.find(x=>x.id===id),last=state.chats[id].at(-1);return `<button class="chatrow" onclick="openChat('${id}')"><img src="${esc(c.avatar)}"><div><b>${esc(c.name)}</b><p>${esc(last.t)}</p></div><span>›</span></button>`}).join('')}</div>`:`<div class="empty"><div>♡</div><h2>Jeszcze z nikim nie rozmawiasz</h2><p>Wybierz personę w Discover.</p><button class="primary" onclick="route('discover')">Odkryj persony</button></div>`}</section>`;}
function creator(){find('page').innerHTML=`<section class="formbox pagepad"><div class="eyebrow">CHARACTER BUILDER</div><h1>Stwórz własną personę</h1><p>Każda persona musi być fikcyjną osobą dorosłą (18+).</p><label>Imię<input id="cn" placeholder="np. Nova"></label><label>Wiek<input id="ca" type="number" min="18" value="25"></label><label>Styl / tag<input id="ct" placeholder="np. Romantyczna, Cyberpunk"></label><label>Opis<input id="cb" placeholder="Krótki opis"></label><label>Osobowość<textarea id="cp" placeholder="np. odważna, zabawna, czuła"></textarea></label><label>Historia<textarea id="cs" placeholder="Backstory postaci"></textarea></label><label>Styl mówienia<input id="cv" placeholder="np. ciepło i z humorem"></label><label>Avatar URL<input id="ci" placeholder="https://..."></label><button class="primary wide" onclick="createChar()">Utwórz personę</button></section>`;}
function createChar(){let age=Math.max(18,+find('ca').value||25),c={id:'c'+Date.now(),name:find('cn').value.trim()||'Nova',age,tag:find('ct').value.trim()||'Original',bio:find('cb').value.trim()||'Nowa persona.',personality:find('cp').value.trim()||'ciekawa i rozmowna',backstory:find('cs').value.trim()||'',voice:find('cv').value.trim()||'naturalnie',avatar:find('ci').value.trim()||avatars[state.chars.length%avatars.length]};state.chars.unshift(c);save();openChat(c.id)}
function gallery(){find('page').innerHTML=`<section class="section pagepad"><div class="sectionhead"><h1>Gallery</h1></div><div class="empty"><div>▣</div><h2>Galeria gotowa na zdjęcia</h2><p>Wersja lokalna nie udaje wygenerowanych obrazów. Po podłączeniu lokalnego generatora obrazów możesz zapisywać tu rezultaty.</p></div></section>`;}
function openChat(id){let c=state.chars.find(x=>x.id===id);if(!c)return;state.chats[id]??=[];state.mem[id]??=[];root.innerHTML=`<div class="chatapp"><header class="chathead"><button onclick="route('discover')">‹</button><img src="${esc(c.avatar)}"><div><b>${esc(c.name)}, ${c.age}</b><small>● online • lokalna pamięć</small></div><button onclick="live('${id}')">◉ Live</button></header><section id="msgs"></section><div class="quick"><button onclick="photoPrompt('${id}')">▣ Zdjęcie</button><button onclick="remember('${id}')">✦ Pamięć</button><button onclick="speakLast('${id}')">♬ Głos</button></div><form id="send"><input id="msg" autocomplete="off" placeholder="Napisz wiadomość…"><button>➤</button></form></div>`;renderChat(id);find('send').onsubmit=e=>{e.preventDefault();send(id)};}
function renderChat(id){let box=find('msgs');box.innerHTML=state.chats[id].map(m=>`<div class="bubble ${m.r}">${esc(m.t)}<small>${new Date(m.ti).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</small></div>`).join('');box.scrollTop=box.scrollHeight}
async function send(id){let input=find('msg'),text=input.value.trim();if(!text)return;input.value='';state.chats[id].push({r:'me',t:text,ti:Date.now()});renderChat(id);save();let c=state.chars.find(x=>x.id===id);let reply=await ai(c,id,text);state.chats[id].push({r:'ai',t:reply,ti:Date.now()});renderChat(id);save();}
async function ai(c,id,text){let history=state.chats[id].slice(-10).map(x=>({role:x.r==='me'?'user':'assistant',content:x.t}));let prompt=`You are ${c.name}, a fictional adult character aged ${c.age}. Personality: ${c.personality}. Backstory: ${c.backstory}. Speaking style: ${c.voice}. Stay in character, be warm, playful and conversational. Never claim to be a real person. User says: ${text}`;try{let base=localStorage.getItem('ollama_url')||'http://localhost:11434/v1/chat/completions';let model=localStorage.getItem('ollama_model')||'llama3.2';let res=await fetch(base,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model,messages:[{role:'system',content:prompt},...history],stream:false})});if(!res.ok)throw Error();let j=await res.json();return j.choices?.[0]?.message?.content||fallback(c,text)}catch(e){return fallback(c,text)}}
function fallback(c,t){let x=t.toLowerCase();if(/hej|cześć|hello/.test(x))return `Hej, to ${c.name}. Miło Cię widzieć 😊 Co dziś chodzi Ci po głowie?`;if(/zdję|photo|fot/.test(x))return `Jasne. Mogę przygotować opis zdjęcia ${c.name} do lokalnego generatora obrazów.`;return `Brzmi interesująco. ${c.name} uśmiecha się i mówi: „Opowiedz mi o tym trochę więcej — chcę Cię lepiej poznać.”`}
function photoPrompt(id){let c=state.chars.find(x=>x.id===id),p=`Portret fikcyjnej dorosłej postaci ${c.name}, wiek ${c.age}, ${c.personality}, styl ${c.tag}, naturalne światło, cinematic, tasteful portrait`;state.chats[id].push({r:'ai',t:`▣ PROMPT DO ZDJĘCIA\n${p}`,ti:Date.now()});save();renderChat(id)}
function remember(id){let c=state.chars.find(x=>x.id===id),v=prompt('Co mam zapamiętać o tej rozmowie?');if(v){state.mem[id].push(v);save();alert(`${c.name}: zapamiętane lokalnie.`)}}
function speakLast(id){let m=state.chats[id]?.filter(x=>x.r==='ai').at(-1);if(m&&speechSynthesis){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(m.t))}}
function live(id){let c=state.chars.find(x=>x.id===id);root.innerHTML=`<div class="live"><button onclick="openChat('${id}')">‹ Wróć</button><img src="${esc(c.avatar)}"><div class="pulse">◉</div><h1>Live z ${esc(c.name)}</h1><p>Tryb głosowy przeglądarki. Kliknij mikrofon i mów.</p><button class="primary mic" id="mic">🎙 Start</button><div id="liveout"></div></div>`;let R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){find('liveout').textContent='Ta przeglądarka nie udostępnia rozpoznawania mowy. Możesz użyć zwykłego czatu.';return}let rec=new R();rec.lang='pl-PL';rec.onresult=e=>{let t=e.results[0][0].transcript;find('liveout').textContent='Ty: '+t;ai(c,id,t).then(r=>{find('liveout').textContent=r;if(speechSynthesis)speechSynthesis.speak(new SpeechSynthesisUtterance(r));state.chats[id].push({r:'me',t,ti:Date.now()},{r:'ai',t:r,ti:Date.now()});save()})};find('mic').onclick=()=>rec.start()}
function start(){if(localStorage.getItem('adult_ok')!=='1'){root.innerHTML=`<div class="gate"><div class="gatecard"><div class="logo">✦</div><h1>AfterDark</h1><h2>Strefa dla dorosłych</h2><p>To aplikacja z fikcyjnymi personami AI. Dostęp wyłącznie dla osób 18+.</p><button class="primary wide" onclick="localStorage.setItem('adult_ok','1');start()">Mam 18 lat — wejdź</button></div></div>`;return}route(state.view||'discover')}
window.route=route;window.openChat=openChat;window.createChar=createChar;window.photoPrompt=photoPrompt;window.remember=remember;window.speakLast=speakLast;window.live=live;start();